name: Deploy PHP App to EC2

on:
    push:
        branches:
            - main  # или нужная ветка

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Upload to EC2 php
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  source: "."
                  target: "~/serv/www_"

            - name: SSH and deploy PHP project
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      cd ~/serv

                      if [ -d "www__" ]; then rm -rf www__; fi

                      if [ -d "www" ]; then mv www www__; fi

                      if [ -d "www_" ]; then mv www_ www; else echo "❌ Ошибка: www_ не найдена"; exit 1; fi

                      echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
                      sed -i 's/__CHENGED_PASSWORD__/${{ secrets.DB_PASSWORD }}/' www/.env

                      docker compose up -d --build

                      docker compose exec -T -w /app php composer install || true

                      if [ -d "www__" ]; then rm -rf www__; fi
